services:
  - type: web
    name: save-your-phone
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true

databases:
  - name: postgres-db
    databaseName: savephone
    user: savephone